### PR TITLE
refactor: update vector sidecar logic to align with the new operator-go version

### PR DESCRIPTION
**Pull request by lwpk110**
1. Refactored the vector log collection sidecar logic to ensure consistency with the latest operator-go version.
2. The vector container no longer uses a standalone image; it now leverages the vector command from the zookeeper product image.

### CODE REVIEW

**Comment by lwpk110** [comment]
@CodiumAI-Agent /review

**Comment by lwpk110** [comment]
> ## PR Reviewer Guide 🔍
> ⏱️ **Estimated effort to review**: 3 🔵🔵🔵⚪⚪
> 🧪 **No relevant tests**
> 🔒 **No security concerns identified**
> ⚡ **Key issues to review**
> 
> [**Refactoring Impact**](https://github.com/zncdatadev/zookeeper-operator/pull/100/files#diff-bc16c37f32c342bbb744fef62c345a3b0ce685d9b11bd93a6f3ae7e6884f8babR137-R137)The change from passing `nil` to `b.GetImage()` in `ExtendWorkloadByVector` function call at line 137 might have implications on how the vector workload is extended. Ensure that the new image handling aligns with the intended use cases and that no unintended side effects occur due to this change.
> 
> [**Image Pull Policy**](https://github.com/zncdatadev/zookeeper-operator/pull/100/files#diff-bc16c37f32c342bbb744fef62c345a3b0ce685d9b11bd93a6f3ae7e6884f8babR170-R185)The addition of `SetImagePullPolicy` at lines 170 and 185 should be reviewed to ensure that the pull policy aligns with the deployment strategies and does not lead to unexpected image update behaviors or access issues in different environments.
> 
> [**Function Documentation**](https://github.com/zncdatadev/zookeeper-operator/pull/100/files#diff-778e2a569518e10966489db15c7deb14e322d5cef48e150564420f65de42dbb7R59-R64)The added documentation for `ExtendWorkloadByVector` at lines 59-64 is verbose and somewhat redundant. Consider simplifying this to make the comments more concise and easier to understand.

review again and improve

**Comment by lwpk110** [comment]
> **[Persistent review](https://github.com/zncdatadev/zookeeper-operator/pull/100#issuecomment-2336560180)** updated to latest commit [c419de8](https://github.com/zncdatadev/zookeeper-operator/commit/c419de859c2614d4e1c5194b377a5a3534f566c8)

preview and improve again

**Comment by lwpk110** [comment]
> **[Persistent review](https://github.com/zncdatadev/zookeeper-operator/pull/100#issuecomment-2336560180)** updated to latest commit [c419de8](https://github.com/zncdatadev/zookeeper-operator/commit/c419de859c2614d4e1c5194b377a5a3534f566c8)

@CodiumAI-Agent  review and improve again

**Review by whg517 — APPROVED** [review]

**Comment by lwpk110** [comment]
> **[Persistent review](https://github.com/zncdatadev/zookeeper-operator/pull/100#issuecomment-2336560180)** updated to latest commit [8493682](https://github.com/zncdatadev/zookeeper-operator/commit/84936823097a65daad8d60a544d8c2e5182f3cf1)

@CodiumAI-Agent review and improve again

**Comment by lwpk110** [comment]
> **[Persistent review](https://github.com/zncdatadev/zookeeper-operator/pull/100#issuecomment-2336560180)** updated to latest commit [179237d](https://github.com/zncdatadev/zookeeper-operator/commit/179237df8f02ac3d9c1399a8cb7167a9c88d2da2)

@CodiumAI-Agent review ti again

**Pull request merged**
